enum GAME_EVENTS {
    GET_SCENE_SIZE = "GET_SCENE_SIZE",
    ON_GET_SCENE_SIZE = "ON_GET_SCENE_SIZE",

    START_PLAY = "START_PLAY",
    PUSH_CARD = "PUSH_CARD",

    LOAD_RESOURCES_PROGRESS = "LOAD_RESOURCES_PROGRESS",
    LOAD_RESOURCES_COMPLETE = "LOAD_RESOURCES_COMPLETE",
    ON_RESIZE_WINDOW = "ON_RESIZE_WINDOW",
    SCENE_INITED = "SCENE_INITED",
    CARD_FLY_FINISH = "CARD_FLY_FINISH",
    CARD_CATCHED = "CARD_CATCHED",
    SHOW_MESSAGE_DLG = "SHOW_MESSAGE_DLG"
};

export default GAME_EVENTS;